/**
 * 语言/国际化状态管理
 * 支持简体中文和英文
 */
import { create } from 'zustand';
import { persist, createJSONStorage } from 'zustand/middleware';
import AsyncStorage from '@react-native-async-storage/async-storage';
import * as Localization from 'expo-localization';

export type Language = 'zh-CN' | 'en';

// 翻译文本
const translations: Record<Language, Record<string, string>> = {
    'zh-CN': {
        // 通用
        'app.name': '心流清单',
        'common.save': '保存',
        'common.cancel': '取消',
        'common.confirm': '确定',
        'common.reset': '重置',
        'common.close': '关闭',
        'common.loading': '加载中...',
        'common.error': '错误',
        'common.success': '成功',
        'common.unset': '未设置',
        'common.unlimited': '不限',
        'common.refresh': '刷新',
        'common.upgradeVip': '升级 VIP',
        'common.tag.free': '免费',
        'common.tag.vip': 'VIP',
        'common.back': '返回',
        'common.edit': '编辑',
        'common.delete': '删除',
        'common.guest': '访客',
        'common.loginRegister': '登录 / 注册',

        // 底部导航
        'nav.today': '今日',
        'nav.home': '首页',
        'nav.calendar': '日历',
        'nav.tasks': '任务',
        'nav.stats': '统计',
        'nav.analytics': '统计',
        'nav.settings': '设置',

        // 设置页
        'settings.title': '设置',
        'settings.developer': '开发者选项',
        'settings.developer.expand': '展开开发者选项',
        'settings.developer.collapse': '收起开发者选项',
        'settings.language': '语言设置',
        'settings.language.auto': '跟随系统',
        'settings.language.zhCN': '简体中文',
        'settings.language.en': 'English',
        'settings.account': '账户管理',
        'settings.account.login': '登录',
        'settings.account.register': '注册',
        'settings.account.logout': '退出登录',
        'settings.account.tier.free': '免费用户',
        'settings.account.tier.vip': 'VIP 用户',
        'settings.developer.subtitle': 'API 配置、调试工具',
        'settings.developer.monitor': '系统状态监控',
        'settings.developer.backendInfo': '后端服务信息',
        'settings.developer.backendInfo.note': '* 如需修改后端地址，请编辑 frontend/store/useConfigStore.ts',
        'settings.developer.managed.title': '服务配置托管',
        'settings.developer.managed.description': 'STT 与 LLM 的模型参数已托管在后端服务 (config.json) 中，前端不再提供修改入口。',
        'settings.debug.logs.title': '交互日志 (Debug)',
        'settings.debug.logs.clear': '清除',
        'settings.debug.logs.empty': '暂无交互记录',
        'settings.debug.logs.input': '输入',
        'settings.alert.connection.success': '连接成功',
        'settings.alert.connection.failure': '连接失败',
        'settings.alert.reset.title': '重置配置',
        'settings.alert.reset.message': '确定要恢复默认设置吗？',
        'settings.alert.save.title': '保存成功',
        'settings.alert.save.message': '配置已更新',
        'settings.models.title': '模型设置',
        'settings.models.group.llm': '语言模型',
        'settings.models.group.vision': '视觉模型',
        'settings.models.group.stt': '语音模型',
        'settings.models.remaining.title': '剩余次数',
        'settings.models.remaining.text': '文字模型',
        'settings.models.remaining.vision': '视觉模型',
        'settings.models.remaining.stt': '语音模型',
        'settings.models.empty': '暂无模型信息',
        'settings.monitor.title': '系统状态监控',
        'settings.monitor.status.waiting': '等待开始',
        'settings.monitor.status.recording': '正在录音...',
        'settings.monitor.status.compressing': '处理音频...',
        'settings.monitor.status.uploading': '上传中...',
        'settings.monitor.status.processingStt': '语音转文字...',
        'settings.monitor.status.processingLlm': 'AI 思考中...',
        'settings.monitor.status.completed': '处理完成',
        'settings.monitor.status.error': '发生错误',
        'settings.monitor.console.title': 'DEBUG CONSOLE',
        'settings.monitor.console.clear': '清除日志',
        'settings.monitor.console.empty': '等待事件...',
        'settings.monitor.simulate': '发送测试请求 (Simulate)',
        'settings.monitor.cancel': '取消请求',

        // 账户与认证
        'account.card.title': '登录账户',
        'account.card.subtitle': '登录后同步数据，解锁更多功能',
        'account.modal.login': '登录',
        'account.modal.register': '注册',
        'account.field.usernameOrUid': '用户名 / UID',
        'account.field.username': '用户名',
        'account.placeholder.usernameOrUid': '请输入用户名或 UID',
        'account.placeholder.username': '请输入用户名',
        'account.field.nickname': '昵称 (可选)',
        'account.placeholder.nickname': '您希望别人怎么称呼您？',
        'account.field.password': '密码',
        'account.placeholder.password': '请输入密码',
        'account.field.confirmPassword': '确认密码',
        'account.placeholder.confirmPassword': '请再次输入密码',
        'account.switch.toRegister': '没有账号？点击注册',
        'account.switch.toLogin': '已有账号？点击登录',
        'account.alert.passwordMismatch': '两次输入的密码不一致',
        'account.alert.passwordLength': '密码长度不能少于6位',
        'account.alert.registerSuccess': '注册成功',
        'account.alert.registerWelcome': '欢迎加入！您的 UID 是',
        'account.alert.logout.title': '退出登录',
        'account.alert.logout.message': '确定要退出当前账号吗？',
        'account.alert.info.title': '账户信息',
        'account.info.uid': 'UID',
        'account.info.username': '用户名',
        'account.info.nickname': '昵称',
        'account.info.nickname.unset': '未设置',
        'account.info.tier': '等级',
        'account.tier.free': '免费用户',
        'account.tier.vip': 'VIP',
        'account.status.notLoggedIn': '未登录',
        'auth.error.passwordMismatch': '两次输入的密码不一致',
        'auth.error.passwordLength': '密码长度不能少于6位',
        'auth.error.usernameTaken': '用户名已被注册',
        'auth.error.missingIdentifier': '请提供用户名或 UID',
        'auth.error.userNotFound': '用户不存在',
        'auth.error.passwordInvalid': '密码错误',

        // API 配置
        'settings.api.backend': '后端 API 服务',
        'settings.api.stt': '语音识别 (STT)',
        'settings.api.llm': 'AI 模型 (LLM)',
        'settings.api.url': 'API URL',
        'settings.api.key': 'API Key',
        'settings.api.model': 'Model ID',
        'settings.api.test': '测试连接',
        'settings.api.save': '保存设置',

        // 事项管理
        'settings.events.title': '全部事项管理',
        'settings.events.subtitle': '查看、编辑或批量删除任务',
        'settings.events.select': '选择',
        'settings.events.cancelSelect': '取消选择',
        'settings.events.deleteSelected': '删除选中',
        'settings.events.confirmDelete': '确定删除选中任务吗？',
        'settings.events.editTitle': '编辑任务',
        'event.field.title': '标题',
        'event.field.time': '时间',
        'event.field.location': '地点',
        'event.field.priority': '优先级',
        'event.priority.low': '低',
        'event.priority.normal': '中',
        'event.priority.high': '高',
        'event.allDay': '全天',

        // 首页
        'home.greeting.morning': '早上好',
        'home.greeting.afternoon': '下午好',
        'home.greeting.evening': '晚上好',
        'home.user': '用户',
        'home.date.weekday.sun': '周日',
        'home.date.weekday.mon': '周一',
        'home.date.weekday.tue': '周二',
        'home.date.weekday.wed': '周三',
        'home.date.weekday.thu': '周四',
        'home.date.weekday.fri': '周五',
        'home.date.weekday.sat': '周六',
        'home.date.month.1': '1月',
        'home.date.month.2': '2月',
        'home.date.month.3': '3月',
        'home.date.month.4': '4月',
        'home.date.month.5': '5月',
        'home.date.month.6': '6月',
        'home.date.month.7': '7月',
        'home.date.month.8': '8月',
        'home.date.month.9': '9月',
        'home.date.month.10': '10月',
        'home.date.month.11': '11月',
        'home.date.month.12': '12月',
        'home.focus.title': '今日聚焦',
        'home.menu.title': '管理任务',
        'home.menu.message': '请选择操作',
        'home.menu.clearAll': '清空所有任务',
        'home.menu.confirm.title': '确认清空',
        'home.menu.confirm.message': '确定要删除所有今日任务吗？此操作无法撤销。',
        'home.menu.confirm.confirm': '确定清空',
        'home.empty.title': '暂无任务',
        'home.empty.subtitle': '点击下方麦克风录制语音添加任务',
        'home.review.title': '今日回顾',
        'home.review.completed.prefix': '你已完成 ',
        'home.review.completed.suffix': ' 的任务。',
        'home.review.praise.high': '太棒了！继续保持！',
        'home.review.praise.mid': '加油，快要完成了！',
        'home.review.praise.low': '还有一些任务等待完成。',
        'home.review.noTasks': '今天还没有任务，试试用语音添加一个吧！',

        // 日历 & 统计占位
        'calendar.title': '日历',
        'calendar.subtitle': '即将推出...',
        'calendar.search.placeholder': '搜索任务、事件或 AI 笔记...',
        'calendar.search.recent': '最近搜索',
        'calendar.search.clear': '清除',
        'calendar.search.suggested': 'AI 建议',
        'calendar.search.suggestion.meetings.title': '近期会议',
        'calendar.search.suggestion.meetings.desc': '快速查找站会与评审',
        'calendar.search.suggestion.completed.title': '已完成任务',
        'calendar.search.suggestion.completed.desc': '回顾你的成就',
        'calendar.today': '今天',
        'calendar.picker.jumpToToday': '回到今天',
        'calendar.noTasks.title': '该日期暂无任务',
        'calendar.noTasks.subtitle': '点击下方语音输入添加任务',
        'stats.title': '数据统计',
        'stats.subtitle': '即将推出...',

        // 语音输入条
        'input.placeholder': '想做什么？',
        'common.tip': '提示',
        'alert.processFailed.title': '处理失败',
        'alert.processFailed.unknown': '未知错误',
        'alert.audioProcessFailed': '处理音频失败',
        'alert.textProcessFailed': '处理文本失败',
        'alert.needLlmKey': '请先在设置中配置 LLM API Key',
        'alert.needApiKeys': '请先在设置中配置 API Key (STT 和 LLM 均需配置)',
        'alert.recordingError': '录音错误',
        'alert.permissionDeniedTitle': '权限不足',
        'alert.permissionDeniedMessage': '该模型仅限 VIP 使用，请升级后重试。',
        'alert.permissionDenied': '未获得相册权限，请在系统设置中允许访问。',
        'alert.imageInvalid': '图片不可用，请重试。',
        'alert.imageTooLarge': '图片仍超过 500KB，请更换或裁剪后再试。',
        'alert.accountBanned.title': '账户已被封禁',
        'alert.accountBanned.message': '该账号已被封禁，已为你退出登录。',
        'log.record.stopProcessing': '停止录音，正在处理音频文件...',
        'log.record.start': '开始录音...',

        // 录音权限/错误
        'error.microphonePermission': '需要麦克风权限才能录制语音',
        'error.permissionRequestFailed': '请求权限失败',
        'error.recordingStartFailed': '开始录音失败',
        'error.recordingStopFailed': '停止录音失败',

        // API & 调试日志
        'api.log.processAudio.start': '开始处理音频请求...',
        'api.log.backendPrefix': '后端地址: ',
        'api.log.fileReadyPrefix': '文件准备就绪: ',
        'api.log.sendingRequest': '正在发送请求到后端...',
        'api.log.requestFailedPrefix': '请求失败: ',
        'api.log.responseParsing': '收到后端响应，正在解析...',
        'api.log.processSuccessPrefix': '处理成功. 识别文本: ',
        'api.log.tasksExtractedPrefix': '提取任务数: ',
        'api.log.businessErrorPrefix': '业务逻辑失败: ',
        'api.log.exceptionPrefix': '异常: ',
        'api.error.apiUrlMissing': '未配置 API URL',
        'api.error.sttKeyMissing': '未配置 STT API Key',
        'api.error.llmKeyMissing': '未配置 LLM API Key',
        'api.log.processText.start': '开始处理文本请求...',
        'api.log.sendingTextPrefix': '发送文本: ',
        'api.log.responseParsingText': '收到响应，解析中...',
        'api.log.processTextDonePrefix': '处理完成. 提取任务数: ',
        'api.error.requestFailedPrefix': '请求失败: ',
        'api.test.missingApiUrl': '未配置 API URL',
        'api.test.missingLlmKey': '未配置 LLM API Key (用于测试连接)',
        'api.test.connectionFailedPrefix': '连接失败: ',
        'api.health.serverErrorPrefix': '服务器错误: ',
        'api.health.connectionFailedPrefix': '连接失败: ',
        'api.log.processImage.start': '开始处理图片请求...',
        'settings.monitor.simulate.text': '这是一个测试任务，请帮我在明早8点提醒我看书',

        // 录音
        'record.start': '点击录音',
        'record.stop': '点击停止',
        'record.processing': 'AI 处理中...',

        // 任务
        'task.add': '添加任务',
        'task.placeholder': '想做什么？',
        'task.today': '今日聚焦',
        'task.completed': '已完成',

        // Web UI
        'web.home.tagline': '准备好征服你的一天了吗？',
        'web.home.quote': '坚持是通向精通的钥匙',
        'web.home.weeklyProgress': '本周进度',
        'web.home.weeklyStatus.onTrack': '保持节奏',
        'web.home.weeklyStatus.better': '比上周更好',
        'web.home.dailyGoal': '每日目标',
        'web.home.tasksRemainingPrefix': '还剩 ',
        'web.home.tasksRemainingSuffix': ' 个任务达成目标。',
        'web.home.activeFocus': '专注中',
        'web.home.activeFocusTask': '项目提案',
        'web.home.aiPrioritizedPrefix': 'AI 已为你优先排好 ',
        'web.home.aiPrioritizedSuffix': ' 个关键任务。',
        'web.home.aiSorted': 'AI 排序',
        'web.home.sampleTask.title': '起草 Q3 战略提案',
        'web.home.sampleTask.badge': '高影响',
        'web.home.sampleTask.estimatePrefix': '预计 ',
        'web.home.sampleTask.estimateSuffix': ' 小时',
        'web.home.sampleTask.category.work': '工作',
        'web.home.addNewTask': '添加新任务',
        'web.home.aiAssistant': 'AI 助手',
        'web.home.insight.title': '昨日洞察',
        'web.home.insight.text': '你在 9:00 - 11:00 的效率最高，完成了 5 小时深度工作，超过平均水平 15%。',
        'web.home.suggestedAction.title': '建议行动',
        'web.home.suggestedAction.text': '为明天上午安排「深度工作」时段，利用你的高峰心流。',
        'web.home.suggestedAction.cta': '安排到 9:00',
        'web.home.habitTracker': '习惯追踪',
        'web.habit.day.mon': '一',
        'web.habit.day.tue': '二',
        'web.habit.day.wed': '三',
        'web.habit.day.thu': '四',
        'web.habit.day.fri': '五',
        'web.habit.day.sat': '六',
        'web.habit.day.sun': '日',
        'web.habit.item.hydration': '补水',
        'web.habit.item.meditation': '冥想',
        'web.habit.item.reading': '阅读',
        'web.habit.item.exercise': '锻炼',

        'web.calendar.title': '日历与洞察',
        'web.calendar.subtitle': '管理日程，追踪你的效率节奏。',
        'web.calendar.newEvent': '新建事件',
        'web.calendar.view.month': '月',
        'web.calendar.view.week': '周',
        'web.calendar.aiInsightTitle': 'AI 洞察',
        'web.calendar.aiInsightText': '你在周二上午通常高出 25% 的产出。建议明早 9 点安排深度工作。',
        'web.calendar.weeklyFocus': '本周专注',
        'web.calendar.nextUp': '接下来',
        'web.calendar.nextUp.sampleTitle': '查看 Q3 财务',
        'web.calendar.nextUp.sampleTime': '今天 14:00',
        'web.calendar.dialog.taskPrefix': '任务：',
        'web.calendar.dialog.timePrefix': '时间：',

        'web.tasks.title': '任务',
        'web.tasks.subtitle': '按项目与分类整理你的心流。',
        'web.tasks.myLists': '我的列表',
        'web.tasks.filter.inbox': '收件箱',
        'web.tasks.filter.personal': '个人',
        'web.tasks.filter.work': '工作',
        'web.tasks.filter.ideas': '想法',
        'web.tasks.filter.projects': '项目',
        'web.tasks.taskCountPrefix': '共 ',
        'web.tasks.taskCountSuffix': ' 项任务',
        'web.tasks.batchDeleteMessagePrefix': '确定删除 ',
        'web.tasks.batchDeleteMessageSuffix': ' 个任务吗？',
        'web.tasks.anytime': '随时',
        'web.tasks.highPriority': '高优先级',
        'web.tasks.editPlaceholder': '这里将显示编辑任务的逻辑。',
        'web.tasks.status': '状态',
        'web.tasks.selectTaskHint': '选择一个任务查看详情',
        'web.tasks.quickAddPlaceholder': '向收件箱添加新任务...',
        'web.tasks.enter': '添加',

        'web.stats.dateRangeSample': '10月24日 - 10月31日, 2023',
        'web.stats.card.flowScore.title': '心流分',
        'web.stats.card.flowScore.desc': '超过 95% 用户',
        'web.stats.card.totalFocus.title': '专注时长',
        'web.stats.card.totalFocus.desc': '较上周 21h 30m',
        'web.stats.card.completionRate.title': '完成率',
        'web.stats.card.completionRate.desc': '有 3 项任务延期',
        'web.stats.card.aiStreak.title': 'AI 连续',
        'web.stats.card.aiStreak.sub': '天',
        'web.stats.card.aiStreak.desc': '个人最佳！',
        'web.stats.deepWorkLegend': '深度工作强度',
        'web.stats.pie.deepWork': '深度工作',
        'web.stats.pie.collaborative': '协作',
        'web.stats.pie.adminOps': '事务管理',
        'web.stats.weeklyFlowTrend': '本周心流走势',
        'web.stats.weeklyFlowTrendSubtitle': '过去 7 天的深度工作强度',
        'web.stats.focusDist': '专注分布',
        'web.stats.focusDistSubtitle': '构成',
        'web.stats.aiReport.title': 'AI 智能报告',
        'web.stats.aiReport.subtitle': '基于你最近 30 天的活动',
        'web.stats.aiReport.viewFull': '查看完整报告',
        'web.stats.aiReport.confirm': '确认安排',
        'web.stats.aiReport.dismiss': '忽略',
        'web.stats.dialog.currentValuePrefix': '当前值：',
        'web.stats.dialog.trendPrefix': '趋势：',
        'web.chat.imageProcessedTitle': '图片已处理',
        'web.chat.imageProcessedPrefix': '图片已压缩至 ',
        'web.chat.imageProcessedSuffix': '，可用于 API。',
        'web.chat.imageProcessFailed': '图片处理失败。',

        // 错误消息
        'error.network': '网络连接失败',
        'error.api': 'API 调用失败',
        'error.login': '登录失败',
        'error.register': '注册失败',
    },
    'en': {
        // Common
        'app.name': 'Project Flow',
        'common.save': 'Save',
        'common.cancel': 'Cancel',
        'common.confirm': 'Confirm',
        'common.reset': 'Reset',
        'common.close': 'Close',
        'common.loading': 'Loading...',
        'common.error': 'Error',
        'common.success': 'Success',
        'common.unset': 'Not set',
        'common.unlimited': 'Unlimited',
        'common.refresh': 'Refresh',
        'common.upgradeVip': 'Upgrade VIP',
        'common.tag.free': 'Free',
        'common.tag.vip': 'VIP',
        'common.back': 'Back',
        'common.edit': 'Edit',
        'common.delete': 'Delete',
        'common.guest': 'Guest',
        'common.loginRegister': 'Login / Register',

        // Bottom Navigation
        'nav.today': 'Today',
        'nav.home': 'Home',
        'nav.calendar': 'Calendar',
        'nav.tasks': 'Tasks',
        'nav.stats': 'Stats',
        'nav.analytics': 'Analytics',
        'nav.settings': 'Settings',

        // Settings
        'settings.title': 'Settings',
        'settings.developer': 'Developer Options',
        'settings.developer.expand': 'Expand Developer Options',
        'settings.developer.collapse': 'Collapse Developer Options',
        'settings.language': 'Language',
        'settings.language.auto': 'System Default',
        'settings.language.zhCN': 'Simplified Chinese',
        'settings.language.en': 'English',
        'settings.account': 'Account',
        'settings.account.login': 'Login',
        'settings.account.register': 'Register',
        'settings.account.logout': 'Logout',
        'settings.account.tier.free': 'Free User',
        'settings.account.tier.vip': 'VIP User',
        'settings.developer.subtitle': 'API config and debug tools',
        'settings.developer.monitor': 'System Status Monitor',
        'settings.developer.backendInfo': 'Backend Service Info',
        'settings.developer.backendInfo.note': '* To change the backend URL, edit frontend/store/useConfigStore.ts',
        'settings.developer.managed.title': 'Managed Service Config',
        'settings.developer.managed.description': 'STT and LLM model parameters are managed in the backend service (config.json). The frontend no longer exposes editable fields.',
        'settings.debug.logs.title': 'Interaction Logs (Debug)',
        'settings.debug.logs.clear': 'Clear',
        'settings.debug.logs.empty': 'No interaction records',
        'settings.debug.logs.input': 'Input',
        'settings.alert.connection.success': 'Connection successful',
        'settings.alert.connection.failure': 'Connection failed',
        'settings.alert.reset.title': 'Reset Settings',
        'settings.alert.reset.message': 'Are you sure you want to restore default settings?',
        'settings.alert.save.title': 'Saved',
        'settings.alert.save.message': 'Settings updated',
        'settings.models.title': 'Model Settings',
        'settings.models.group.llm': 'Language Models',
        'settings.models.group.vision': 'Vision Models',
        'settings.models.group.stt': 'Speech Models',
        'settings.models.remaining.title': 'Remaining Quota',
        'settings.models.remaining.text': 'Text Models',
        'settings.models.remaining.vision': 'Vision Models',
        'settings.models.remaining.stt': 'Speech Models',
        'settings.models.empty': 'No model info',
        'settings.monitor.title': 'System Status Monitor',
        'settings.monitor.status.waiting': 'Waiting to start',
        'settings.monitor.status.recording': 'Recording...',
        'settings.monitor.status.compressing': 'Processing audio...',
        'settings.monitor.status.uploading': 'Uploading...',
        'settings.monitor.status.processingStt': 'Speech to text...',
        'settings.monitor.status.processingLlm': 'AI is thinking...',
        'settings.monitor.status.completed': 'Completed',
        'settings.monitor.status.error': 'Error occurred',
        'settings.monitor.console.title': 'DEBUG CONSOLE',
        'settings.monitor.console.clear': 'Clear Logs',
        'settings.monitor.console.empty': 'Waiting for events...',
        'settings.monitor.simulate': 'Send test request (Simulate)',
        'settings.monitor.cancel': 'Cancel Request',

        // Account & Auth
        'account.card.title': 'Sign in',
        'account.card.subtitle': 'Sign in to sync data and unlock more features',
        'account.modal.login': 'Login',
        'account.modal.register': 'Register',
        'account.field.usernameOrUid': 'Username / UID',
        'account.field.username': 'Username',
        'account.placeholder.usernameOrUid': 'Enter username or UID',
        'account.placeholder.username': 'Enter username',
        'account.field.nickname': 'Nickname (optional)',
        'account.placeholder.nickname': 'How should others address you?',
        'account.field.password': 'Password',
        'account.placeholder.password': 'Enter password',
        'account.field.confirmPassword': 'Confirm password',
        'account.placeholder.confirmPassword': 'Re-enter password',
        'account.switch.toRegister': 'No account? Tap to register',
        'account.switch.toLogin': 'Already have an account? Tap to login',
        'account.alert.passwordMismatch': 'Passwords do not match',
        'account.alert.passwordLength': 'Password must be at least 6 characters',
        'account.alert.registerSuccess': 'Registration successful',
        'account.alert.registerWelcome': 'Welcome! Your UID is',
        'account.alert.logout.title': 'Logout',
        'account.alert.logout.message': 'Are you sure you want to log out?',
        'account.alert.info.title': 'Account Info',
        'account.info.uid': 'UID',
        'account.info.username': 'Username',
        'account.info.nickname': 'Nickname',
        'account.info.nickname.unset': 'Not set',
        'account.info.tier': 'Tier',
        'account.tier.free': 'Free',
        'account.tier.vip': 'VIP',
        'account.status.notLoggedIn': 'Not Logged In',
        'auth.error.passwordMismatch': 'Passwords do not match',
        'auth.error.passwordLength': 'Password must be at least 6 characters',
        'auth.error.usernameTaken': 'Username is already taken',
        'auth.error.missingIdentifier': 'Please provide a username or UID',
        'auth.error.userNotFound': 'User not found',
        'auth.error.passwordInvalid': 'Incorrect password',

        // API Config
        'settings.api.backend': 'Backend API',
        'settings.api.stt': 'Speech to Text (STT)',
        'settings.api.llm': 'AI Model (LLM)',
        'settings.api.url': 'API URL',
        'settings.api.key': 'API Key',
        'settings.api.model': 'Model ID',
        'settings.api.test': 'Test Connection',
        'settings.api.save': 'Save Settings',

        // Event Management
        'settings.events.title': 'Manage All Events',
        'settings.events.subtitle': 'View, edit, or bulk delete tasks',
        'settings.events.select': 'Select',
        'settings.events.cancelSelect': 'Cancel',
        'settings.events.deleteSelected': 'Delete Selected',
        'settings.events.confirmDelete': 'Delete selected tasks?',
        'settings.events.editTitle': 'Edit Event',
        'event.field.title': 'Title',
        'event.field.time': 'Time',
        'event.field.location': 'Location',
        'event.field.priority': 'Priority',
        'event.priority.low': 'Low',
        'event.priority.normal': 'Normal',
        'event.priority.high': 'High',
        'event.allDay': 'All Day',

        // Home
        'home.greeting.morning': 'Good morning',
        'home.greeting.afternoon': 'Good afternoon',
        'home.greeting.evening': 'Good evening',
        'home.user': 'User',
        'home.date.weekday.sun': 'Sun',
        'home.date.weekday.mon': 'Mon',
        'home.date.weekday.tue': 'Tue',
        'home.date.weekday.wed': 'Wed',
        'home.date.weekday.thu': 'Thu',
        'home.date.weekday.fri': 'Fri',
        'home.date.weekday.sat': 'Sat',
        'home.date.month.1': 'Jan',
        'home.date.month.2': 'Feb',
        'home.date.month.3': 'Mar',
        'home.date.month.4': 'Apr',
        'home.date.month.5': 'May',
        'home.date.month.6': 'Jun',
        'home.date.month.7': 'Jul',
        'home.date.month.8': 'Aug',
        'home.date.month.9': 'Sep',
        'home.date.month.10': 'Oct',
        'home.date.month.11': 'Nov',
        'home.date.month.12': 'Dec',
        'home.focus.title': 'Today\'s Focus',
        'home.menu.title': 'Manage Tasks',
        'home.menu.message': 'Please choose an action',
        'home.menu.clearAll': 'Clear all tasks',
        'home.menu.confirm.title': 'Confirm Clear',
        'home.menu.confirm.message': 'Are you sure you want to delete all today\'s tasks? This cannot be undone.',
        'home.menu.confirm.confirm': 'Clear all',
        'home.empty.title': 'No tasks yet',
        'home.empty.subtitle': 'Tap the mic below to add tasks by voice',
        'home.review.title': 'Today\'s Review',
        'home.review.completed.prefix': 'You have completed ',
        'home.review.completed.suffix': ' of your tasks.',
        'home.review.praise.high': 'Awesome! Keep it up!',
        'home.review.praise.mid': 'Nice work — almost there!',
        'home.review.praise.low': 'You still have a few tasks to finish.',
        'home.review.noTasks': 'No tasks yet today. Try adding one by voice!',

        // Calendar & Stats placeholder
        'calendar.title': 'Calendar',
        'calendar.subtitle': 'Coming soon...',
        'calendar.search.placeholder': 'Search tasks, events, or AI notes...',
        'calendar.search.recent': 'Recent Searches',
        'calendar.search.clear': 'Clear',
        'calendar.search.suggested': 'Suggested by AI',
        'calendar.search.suggestion.meetings.title': 'Upcoming Meetings',
        'calendar.search.suggestion.meetings.desc': 'Quickly find your standups and reviews.',
        'calendar.search.suggestion.completed.title': 'Completed Tasks',
        'calendar.search.suggestion.completed.desc': 'Review what you\'ve accomplished.',
        'calendar.today': 'Today',
        'calendar.picker.jumpToToday': 'Jump to Today',
        'calendar.noTasks.title': 'No tasks for this day',
        'calendar.noTasks.subtitle': 'Tap the mic below to add tasks by voice',
        'stats.title': 'Stats',
        'stats.subtitle': 'Coming soon...',

        // Voice input bar
        'input.placeholder': 'What do you want to do?',
        'common.tip': 'Tip',
        'alert.processFailed.title': 'Processing failed',
        'alert.processFailed.unknown': 'Unknown error',
        'alert.audioProcessFailed': 'Audio processing failed',
        'alert.textProcessFailed': 'Text processing failed',
        'alert.needLlmKey': 'Please configure the LLM API Key in Settings first',
        'alert.needApiKeys': 'Please configure API Keys in Settings (both STT and LLM are required)',
        'alert.recordingError': 'Recording error',
        'alert.permissionDeniedTitle': 'Permission Required',
        'alert.permissionDeniedMessage': 'This model is VIP-only. Please upgrade to continue.',
        'alert.permissionDenied': 'Photo access denied. Please enable it in system settings.',
        'alert.imageInvalid': 'Image is invalid. Please try again.',
        'alert.imageTooLarge': 'Image is still over 500KB. Please try another image.',
        'alert.accountBanned.title': 'Account Banned',
        'alert.accountBanned.message': 'This account has been banned. You have been logged out.',
        'log.record.stopProcessing': 'Stopped recording. Processing audio file...',
        'log.record.start': 'Started recording...',

        // Recording permissions/errors
        'error.microphonePermission': 'Microphone permission is required to record',
        'error.permissionRequestFailed': 'Permission request failed',
        'error.recordingStartFailed': 'Failed to start recording',
        'error.recordingStopFailed': 'Failed to stop recording',

        // API & debug logs
        'api.log.processAudio.start': 'Starting audio processing...',
        'api.log.backendPrefix': 'Backend URL: ',
        'api.log.fileReadyPrefix': 'File ready: ',
        'api.log.sendingRequest': 'Sending request to backend...',
        'api.log.requestFailedPrefix': 'Request failed: ',
        'api.log.responseParsing': 'Response received. Parsing...',
        'api.log.processSuccessPrefix': 'Success. Recognized text: ',
        'api.log.tasksExtractedPrefix': 'Tasks extracted: ',
        'api.log.businessErrorPrefix': 'Business logic failed: ',
        'api.log.exceptionPrefix': 'Exception: ',
        'api.error.apiUrlMissing': 'API URL not configured',
        'api.error.sttKeyMissing': 'STT API Key not configured',
        'api.error.llmKeyMissing': 'LLM API Key not configured',
        'api.log.processText.start': 'Starting text processing...',
        'api.log.sendingTextPrefix': 'Sending text: ',
        'api.log.responseParsingText': 'Response received. Parsing...',
        'api.log.processTextDonePrefix': 'Processing complete. Tasks extracted: ',
        'api.error.requestFailedPrefix': 'Request failed: ',
        'api.test.missingApiUrl': 'API URL not configured',
        'api.test.missingLlmKey': 'LLM API Key not configured (required for testing)',
        'api.test.connectionFailedPrefix': 'Connection failed: ',
        'api.health.serverErrorPrefix': 'Server error: ',
        'api.health.connectionFailedPrefix': 'Connection failed: ',
        'api.log.processImage.start': 'Starting image processing...',
        'settings.monitor.simulate.text': 'This is a test task. Please remind me to read at 8 AM tomorrow.',

        // Recording
        'record.start': 'Tap to Record',
        'record.stop': 'Tap to Stop',
        'record.processing': 'AI Processing...',

        // Tasks
        'task.add': 'Add Task',
        'task.placeholder': 'What do you want to do?',
        'task.today': 'Today\'s Focus',
        'task.completed': 'Completed',

        // Web UI
        'web.home.tagline': 'Ready to conquer your day?',
        'web.home.quote': 'Consistency is the key to mastery',
        'web.home.weeklyProgress': 'Weekly Progress',
        'web.home.weeklyStatus.onTrack': 'On Track',
        'web.home.weeklyStatus.better': 'Better than last week',
        'web.home.dailyGoal': 'Daily Goal',
        'web.home.tasksRemainingPrefix': '',
        'web.home.tasksRemainingSuffix': ' tasks remaining to hit your target.',
        'web.home.activeFocus': 'Active Focus',
        'web.home.activeFocusTask': 'Project Proposal',
        'web.home.aiPrioritizedPrefix': 'AI has prioritized ',
        'web.home.aiPrioritizedSuffix': ' critical tasks for you.',
        'web.home.aiSorted': 'AI Sorted',
        'web.home.sampleTask.title': 'Draft Q3 Strategy Proposal',
        'web.home.sampleTask.badge': 'High Impact',
        'web.home.sampleTask.estimatePrefix': '',
        'web.home.sampleTask.estimateSuffix': 'h est',
        'web.home.sampleTask.category.work': 'Work',
        'web.home.addNewTask': 'Add new task',
        'web.home.aiAssistant': 'AI Assistant',
        'web.home.insight.title': 'Yesterday\'s Insight',
        'web.home.insight.text': 'You were most productive between 9:00 AM - 11:00 AM. You completed 5 deep work hours, beating your average by 15%.',
        'web.home.suggestedAction.title': 'Suggested Action',
        'web.home.suggestedAction.text': 'Schedule your "Deep Work" block for tomorrow morning to leverage your peak flow state.',
        'web.home.suggestedAction.cta': 'Schedule for 9:00 AM',
        'web.home.habitTracker': 'Habit Tracker',
        'web.habit.day.mon': 'M',
        'web.habit.day.tue': 'T',
        'web.habit.day.wed': 'W',
        'web.habit.day.thu': 'T',
        'web.habit.day.fri': 'F',
        'web.habit.day.sat': 'S',
        'web.habit.day.sun': 'S',
        'web.habit.item.hydration': 'Hydration',
        'web.habit.item.meditation': 'Meditation',
        'web.habit.item.reading': 'Reading',
        'web.habit.item.exercise': 'Exercise',

        'web.calendar.title': 'Calendar & Insights',
        'web.calendar.subtitle': 'Manage your schedule and track your productivity flow.',
        'web.calendar.newEvent': 'New Event',
        'web.calendar.view.month': 'Month',
        'web.calendar.view.week': 'Week',
        'web.calendar.aiInsightTitle': 'AI Insight',
        'web.calendar.aiInsightText': 'You\'re usually 25% more productive on Tuesday mornings. Try scheduling deep work for tomorrow at 9 AM.',
        'web.calendar.weeklyFocus': 'Weekly Focus',
        'web.calendar.nextUp': 'Next Up',
        'web.calendar.nextUp.sampleTitle': 'Review Q3 Financials',
        'web.calendar.nextUp.sampleTime': 'Today, 2:00 PM',
        'web.calendar.dialog.taskPrefix': 'Task: ',
        'web.calendar.dialog.timePrefix': 'Time: ',

        'web.tasks.title': 'Tasks',
        'web.tasks.subtitle': 'Organize your flow by projects and categories.',
        'web.tasks.myLists': 'My Lists',
        'web.tasks.filter.inbox': 'Inbox',
        'web.tasks.filter.personal': 'Personal',
        'web.tasks.filter.work': 'Work',
        'web.tasks.filter.ideas': 'Ideas',
        'web.tasks.filter.projects': 'Projects',
        'web.tasks.taskCountPrefix': '',
        'web.tasks.taskCountSuffix': ' tasks',
        'web.tasks.batchDeleteMessagePrefix': 'Delete ',
        'web.tasks.batchDeleteMessageSuffix': ' tasks?',
        'web.tasks.anytime': 'Anytime',
        'web.tasks.highPriority': 'High Priority',
        'web.tasks.editPlaceholder': 'Edit task logic here...',
        'web.tasks.status': 'Status',
        'web.tasks.selectTaskHint': 'Select a task to view details',
        'web.tasks.quickAddPlaceholder': 'Add a new task to Inbox...',
        'web.tasks.enter': 'Enter',

        'web.stats.dateRangeSample': 'Oct 24 - Oct 31, 2023',
        'web.stats.card.flowScore.title': 'Flow Score',
        'web.stats.card.flowScore.desc': 'Top 5% of users',
        'web.stats.card.totalFocus.title': 'Total Focus',
        'web.stats.card.totalFocus.desc': 'vs 21h 30m last week',
        'web.stats.card.completionRate.title': 'Completion Rate',
        'web.stats.card.completionRate.desc': '3 tasks rolled over',
        'web.stats.card.aiStreak.title': 'AI Streak',
        'web.stats.card.aiStreak.sub': 'Days',
        'web.stats.card.aiStreak.desc': 'Personal best!',
        'web.stats.deepWorkLegend': 'Deep Work Intensity',
        'web.stats.pie.deepWork': 'Deep Work',
        'web.stats.pie.collaborative': 'Collaborative',
        'web.stats.pie.adminOps': 'Admin & Ops',
        'web.stats.weeklyFlowTrend': 'Weekly Flow Trend',
        'web.stats.weeklyFlowTrendSubtitle': 'Deep work intensity over last 7 days',
        'web.stats.focusDist': 'Focus Dist.',
        'web.stats.focusDistSubtitle': 'Breakdown',
        'web.stats.aiReport.title': 'AI Intelligence Report',
        'web.stats.aiReport.subtitle': 'Based on your last 30 days of activity',
        'web.stats.aiReport.viewFull': 'View Full Report',
        'web.stats.aiReport.confirm': 'Confirm Block',
        'web.stats.aiReport.dismiss': 'Dismiss',
        'web.stats.dialog.currentValuePrefix': 'Current Value: ',
        'web.stats.dialog.trendPrefix': 'Trend: ',
        'web.chat.imageProcessedTitle': 'Image Processed',
        'web.chat.imageProcessedPrefix': 'Image compressed to ',
        'web.chat.imageProcessedSuffix': '. Ready for API.',
        'web.chat.imageProcessFailed': 'Image processing failed.',

        // Error Messages
        'error.network': 'Network connection failed',
        'error.api': 'API call failed',
        'error.login': 'Login failed',
        'error.register': 'Registration failed',
    },
};

interface LanguageState {
    // 当前语言
    language: Language;
    // 是否自动检测
    autoDetect: boolean;

    // Actions
    setLanguage: (lang: Language) => void;
    setAutoDetect: (auto: boolean) => void;
    t: (key: string) => string;
    detectSystemLanguage: () => Language;
}

export const useLanguageStore = create<LanguageState>()(
    persist(
        (set, get) => ({
            language: 'zh-CN',
            autoDetect: true,

            setLanguage: (lang) => set({ language: lang, autoDetect: false }),

            setAutoDetect: (auto) => {
                if (auto) {
                    const detected = get().detectSystemLanguage();
                    set({ autoDetect: true, language: detected });
                } else {
                    set({ autoDetect: false });
                }
            },

            t: (key) => {
                const { language } = get();
                return translations[language]?.[key] || key;
            },

            detectSystemLanguage: () => {
                const locales = Localization.getLocales();
                const primaryLocale = locales[0]?.languageCode || 'zh';

                if (primaryLocale === 'zh') {
                    return 'zh-CN';
                }
                return 'en';
            },
        }),
        {
            name: 'project-flow-language',
            storage: createJSONStorage(() => AsyncStorage),
            partialize: (state) => ({
                language: state.language,
                autoDetect: state.autoDetect,
            }),
            onRehydrateStorage: () => (state) => {
                // 如果设置为自动检测，在加载后重新检测系统语言
                if (state?.autoDetect) {
                    const detected = state.detectSystemLanguage();
                    state.language = detected;
                }
            },
        }
    )
);
